/**
 * Email unsubscribe handler.
 *
 * URL format:  GET /api/unsubscribe?c=<contactId>&sig=<hmac>
 *
 * The token is HMAC-SHA256(contactId, INTERNAL_AI_REVIEW_SECRET).
 * Generated by sage-email-smtp when appending the unsubscribe footer.
 *
 * On success:
 *   - Sets email_opt_out = true on sage_contacts
 *   - Writes email_unsubscribed to message_events
 *   - Escalates all active automations for the contact
 *   - Returns a simple HTML confirmation page
 */

import { NextRequest, NextResponse } from 'next/server'
import { createHmac } from 'crypto'
import { createAdminClient } from '@/lib/supabase/server'
import { escalateAutomationsForOptOut } from '@/app/actions/automations'

export const dynamic = 'force-dynamic'

function verifyToken(contactId: string, sig: string): boolean {
  const secret = process.env.INTERNAL_AI_REVIEW_SECRET
  if (!secret) return false
  const expected = createHmac('sha256', secret).update(contactId).digest('hex')
  return expected === sig
}

const PAGE_OK = (name: string) => `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Unsubscribed</title>
  <style>
    body { font-family: -apple-system, sans-serif; display: flex; align-items: center;
           justify-content: center; min-height: 100vh; margin: 0; background: #f9fafb; color: #111; }
    .card { background: #fff; border-radius: 16px; padding: 40px 48px; max-width: 440px;
            text-align: center; box-shadow: 0 4px 24px rgba(0,0,0,.08); }
    h1 { font-size: 20px; font-weight: 700; margin: 0 0 8px; }
    p  { font-size: 14px; color: #6b7280; margin: 0; line-height: 1.6; }
    .check { font-size: 40px; margin-bottom: 16px; }
  </style>
</head>
<body>
  <div class="card">
    <div class="check">✓</div>
    <h1>You've been unsubscribed</h1>
    <p>Hi ${name ? `${name}, ` : ''}you'll no longer receive emails from us.<br />
       You can reply to any of our previous emails if you change your mind.</p>
  </div>
</body>
</html>`

const PAGE_ERR = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>Invalid link</title>
  <style>
    body { font-family: -apple-system, sans-serif; display: flex; align-items: center;
           justify-content: center; min-height: 100vh; margin: 0; background: #f9fafb; }
    .card { background: #fff; border-radius: 16px; padding: 40px 48px; max-width: 440px;
            text-align: center; box-shadow: 0 4px 24px rgba(0,0,0,.08); }
    h1 { font-size: 20px; font-weight: 700; margin: 0 0 8px; color: #111; }
    p  { font-size: 14px; color: #6b7280; margin: 0; }
  </style>
</head>
<body>
  <div class="card">
    <h1>Invalid link</h1>
    <p>This unsubscribe link is invalid or has already been used.<br />
       Reply "UNSUBSCRIBE" to any of our emails to opt out.</p>
  </div>
</body>
</html>`

export async function GET(req: NextRequest) {
  const { searchParams } = req.nextUrl
  const contactId = searchParams.get('c')
  const sig       = searchParams.get('sig')

  if (!contactId || !sig || !verifyToken(contactId, sig)) {
    return new NextResponse(PAGE_ERR, {
      status:  400,
      headers: { 'Content-Type': 'text/html; charset=utf-8' },
    })
  }

  const admin = createAdminClient()

  // Look up contact to get workspace_id and name
  const { data: contact } = await admin
    .from('sage_contacts')
    .select('id, workspace_id, name, email_opt_out')
    .eq('id', contactId)
    .single()

  if (!contact) {
    return new NextResponse(PAGE_ERR, {
      status:  400,
      headers: { 'Content-Type': 'text/html; charset=utf-8' },
    })
  }

  // Idempotent — already unsubscribed
  if (!contact.email_opt_out) {
    const now = new Date().toISOString()

    await admin
      .from('sage_contacts')
      .update({ email_opt_out: true, email_opted_out_at: now })
      .eq('id', contactId)

    // Write message_events row
    await admin.from('message_events').insert({
      workspace_id: contact.workspace_id,
      channel:      'email',
      contact_id:   contactId,
      event_type:   'email_unsubscribed',
      provider:     'unsubscribe_link',
      event_at:     now,
    })

    // Escalate active automations so AI surfaces the opt-out
    void escalateAutomationsForOptOut(
      contactId,
      contact.workspace_id,
      'Contact clicked email unsubscribe',
    ).catch(() => {})
  }

  return new NextResponse(PAGE_OK(contact.name ?? ''), {
    status:  200,
    headers: { 'Content-Type': 'text/html; charset=utf-8' },
  })
}
