import { supabase } from '../lib/supabase.js'
import type { ToolExecutionContext } from './agent/tools.js'

export interface DocumentToolInput {
  type:     string   // 'proposal' | 'report' | 'summary' | 'custom'
  title:    string
  content:  string   // Markdown or plain text from Claude
}

/**
 * Wraps Claude-generated content in a clean HTML document,
 * uploads it to Supabase Storage, and returns a signed URL.
 */
export async function generateDocumentTool(
  input: DocumentToolInput,
  ctx:   ToolExecutionContext,
): Promise<string> {
  const { type, title, content } = input

  const html = buildHtmlDocument(title, content)
  const bytes = Buffer.from(html, 'utf-8')

  const fileName  = `${ctx.workspaceId}/${Date.now()}-${slugify(title)}.html`
  const storageBucket = 'documents'

  const { error: uploadError } = await supabase.storage
    .from(storageBucket)
    .upload(fileName, bytes, {
      contentType: 'text/html',
      upsert:      false,
    })

  if (uploadError) {
    return `Document generation failed: ${uploadError.message}`
  }

  const { data: signed } = await supabase.storage
    .from(storageBucket)
    .createSignedUrl(fileName, 60 * 60 * 24 * 7) // 7-day link

  if (!signed?.signedUrl) {
    return `Document created but could not generate download link.`
  }

  console.log(`[document-generator] ${type} "${title}" → ${fileName} workspace=${ctx.workspaceId}`)

  return `${type.charAt(0).toUpperCase() + type.slice(1)} "${title}" is ready. Download link (valid 7 days): ${signed.signedUrl}`
}

function slugify(str: string): string {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '')
    .slice(0, 60)
}

function buildHtmlDocument(title: string, content: string): string {
  // Convert basic markdown to HTML (bold, headers, lists, line breaks)
  const body = content
    .replace(/^### (.+)$/gm, '<h3>$1</h3>')
    .replace(/^## (.+)$/gm,  '<h2>$1</h2>')
    .replace(/^# (.+)$/gm,   '<h1>$1</h1>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g,    '<em>$1</em>')
    .replace(/^- (.+)$/gm,   '<li>$1</li>')
    .replace(/(<li>.*<\/li>\n?)+/g, (m) => `<ul>${m}</ul>`)
    .replace(/\n{2,}/g, '</p><p>')
    .replace(/\n/g, '<br />')

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHtml(title)}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 760px; margin: 48px auto; padding: 0 24px; color: #111; line-height: 1.7; }
    h1 { font-size: 28px; font-weight: 700; margin-bottom: 8px; }
    h2 { font-size: 20px; font-weight: 600; margin-top: 32px; }
    h3 { font-size: 16px; font-weight: 600; margin-top: 24px; }
    p  { margin: 12px 0; }
    ul { padding-left: 24px; }
    li { margin: 4px 0; }
    .meta { font-size: 13px; color: #888; margin-bottom: 32px; padding-bottom: 16px; border-bottom: 1px solid #eee; }
    @media print { body { margin: 24px; } }
  </style>
</head>
<body>
  <h1>${escapeHtml(title)}</h1>
  <p class="meta">Generated by Appalix AI · ${new Date().toLocaleDateString('en-AU', { dateStyle: 'long' })}</p>
  <p>${body}</p>
</body>
</html>`
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g,  '&amp;')
    .replace(/</g,  '&lt;')
    .replace(/>/g,  '&gt;')
    .replace(/"/g,  '&quot;')
}
