import type { Metadata } from 'next'
import { createClient } from '@/lib/supabase/server'
import { redirect } from 'next/navigation'
import { SageToolbar } from '@/components/dashboard/sage-toolbar'
import { AutomationsClient } from './automations-client'
import { getActivityFeed, resolveViewingAs } from '@/app/actions/activity-feed'
import type { AutomationListItem } from '@/lib/types'

export const metadata: Metadata = { title: 'Automations · Sage' }

// ── Mock data matching exact AutomationListItem shape ─────────────────────────
// Replace with real service calls once migration is applied:
//   const [active, attention, insights] = await Promise.all([
//     getActiveAutomations(),
//     getNeedsAttention(),
//     getAutomationInsights(),
//   ])

const h  = (n: number) => new Date(Date.now() - n * 60 * 60 * 1000).toISOString()
const d  = (n: number) => new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString()
const fh = (n: number) => new Date(Date.now() + n * 60 * 60 * 1000).toISOString()
const fd = (n: number) => new Date(Date.now() + n * 24 * 60 * 60 * 1000).toISOString()

const MOCK_ACTIVE: AutomationListItem[] = [

  // ── Needs Attention (engaged / escalated) — 10 leads ─────────────────────
  {
    id: 'a1', workspace_id: 'ws1', contact_id: 'c1', deal_id: null,
    source_type: 'prospect', source_ref_id: null,
    goal: 'warm_introduction', primary_channel: 'email', fallback_channel: 'sms',
    status: 'engaged', stage: 'engagement_detected',
    priority: 'high', momentum: 'increasing',
    next_action_type: 'send_email', next_action_at: fh(2),
    current_summary: 'Replied to intro email within 4 hours. Expressed interest in the enterprise tier. Mentioned Q3 budget review.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(4), last_engagement_at: h(4),
    step_count: 2, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(2), updated_at: h(4),
    contact_name: 'Sarah Mitchell', contact_email: 'sarah@acmecorp.com', contact_phone: null, deal_title: null,
  },
  {
    id: 'a2', workspace_id: 'ws1', contact_id: 'c2', deal_id: 'd1',
    source_type: 'form', source_ref_id: null,
    goal: 'meeting_conversion', primary_channel: 'email', fallback_channel: 'sms',
    status: 'escalated', stage: 'handoff_ready',
    priority: 'high', momentum: 'increasing',
    next_action_type: 'handoff', next_action_at: null,
    current_summary: 'Requested a demo call. Mentioned specific integration requirements. Ready for human handoff.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(1), last_engagement_at: h(1),
    step_count: 4, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(6), updated_at: h(1),
    contact_name: 'Tom Eriksson', contact_email: 'tom@nordic-ventures.se', contact_phone: null, deal_title: 'Nordic Ventures — Enterprise',
  },
  {
    id: 'a3', workspace_id: 'ws1', contact_id: 'c3', deal_id: null,
    source_type: 'email', source_ref_id: null,
    goal: 'qualification', primary_channel: 'email', fallback_channel: null,
    status: 'engaged', stage: 'engagement_detected',
    priority: 'high', momentum: 'increasing',
    next_action_type: 'send_email', next_action_at: fh(3),
    current_summary: 'Opened all 3 emails and clicked pricing link twice. Asked about annual billing. Strong buying signal.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(2), last_engagement_at: h(2),
    step_count: 3, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(4), updated_at: h(2),
    contact_name: 'Lena Hoffmann', contact_email: 'lena@bluestack.de', contact_phone: null, deal_title: null,
  },
  {
    id: 'a4', workspace_id: 'ws1', contact_id: 'c4', deal_id: 'd3',
    source_type: 'bot', source_ref_id: null,
    goal: 'meeting_conversion', primary_channel: 'sms', fallback_channel: 'email',
    status: 'escalated', stage: 'handoff_ready',
    priority: 'high', momentum: 'increasing',
    next_action_type: 'handoff', next_action_at: null,
    current_summary: 'Replied via SMS asking for availability this week. Confirmed budget is approved. Immediate handoff needed.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(0), last_engagement_at: h(0),
    step_count: 5, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(3), updated_at: h(0),
    contact_name: 'Marcus Reid', contact_email: 'marcus@apexlogistics.com', contact_phone: '+13105550192', deal_title: 'Apex Logistics — Pro',
  },
  {
    id: 'a5', workspace_id: 'ws1', contact_id: 'c5', deal_id: null,
    source_type: 'prospect', source_ref_id: null,
    goal: 'warm_introduction', primary_channel: 'email', fallback_channel: null,
    status: 'engaged', stage: 'engagement_detected',
    priority: 'medium', momentum: 'increasing',
    next_action_type: 'send_email', next_action_at: fh(5),
    current_summary: 'Replied asking for a case study. Works at a 200-person SaaS company. Mentioned evaluating 3 vendors.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(6), last_engagement_at: h(6),
    step_count: 2, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(3), updated_at: h(6),
    contact_name: 'Yuki Tanaka', contact_email: 'yuki@cloudnine.jp', contact_phone: null, deal_title: null,
  },
  {
    id: 'a6', workspace_id: 'ws1', contact_id: 'c6', deal_id: 'd4',
    source_type: 'email', source_ref_id: null,
    goal: 'meeting_conversion', primary_channel: 'email', fallback_channel: 'sms',
    status: 'engaged', stage: 'engagement_detected',
    priority: 'high', momentum: 'increasing',
    next_action_type: 'send_email', next_action_at: fh(1),
    current_summary: 'Replied to follow-up. Wants to loop in their CTO before the demo. Strong intent.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(3), last_engagement_at: h(3),
    step_count: 3, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(5), updated_at: h(3),
    contact_name: 'Fatima Al-Rashid', contact_email: 'fatima@horizonvc.ae', contact_phone: null, deal_title: 'Horizon VC — Team Plan',
  },
  {
    id: 'a7', workspace_id: 'ws1', contact_id: 'c7', deal_id: null,
    source_type: 'prospect', source_ref_id: null,
    goal: 'qualification', primary_channel: 'email', fallback_channel: null,
    status: 'escalated', stage: 'handoff_ready',
    priority: 'high', momentum: 'increasing',
    next_action_type: 'handoff', next_action_at: null,
    current_summary: 'Replied with a detailed product question that requires sales knowledge. Escalated for human response.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(2), last_engagement_at: h(2),
    step_count: 2, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(2), updated_at: h(2),
    contact_name: 'Chidi Obi', contact_email: 'chidi@finbridge.ng', contact_phone: null, deal_title: null,
  },
  {
    id: 'a8', workspace_id: 'ws1', contact_id: 'c8', deal_id: 'd5',
    source_type: 'form', source_ref_id: null,
    goal: 'meeting_conversion', primary_channel: 'email', fallback_channel: 'sms',
    status: 'engaged', stage: 'engagement_detected',
    priority: 'medium', momentum: 'flat',
    next_action_type: 'send_email', next_action_at: fd(1),
    current_summary: 'Clicked call-to-action but did not book. Needs a nudge with a direct calendar link.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(12), last_engagement_at: h(12),
    step_count: 3, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(4), updated_at: h(12),
    contact_name: 'Nina Petrova', contact_email: 'nina@softwave.ru', contact_phone: null, deal_title: 'Softwave — Starter',
  },
  {
    id: 'a9', workspace_id: 'ws1', contact_id: 'c9', deal_id: null,
    source_type: 'bot', source_ref_id: null,
    goal: 'warm_introduction', primary_channel: 'sms', fallback_channel: null,
    status: 'engaged', stage: 'engagement_detected',
    priority: 'medium', momentum: 'increasing',
    next_action_type: 'send_sms', next_action_at: fh(4),
    current_summary: 'Responded to SMS intro positively. Asked about pricing tiers. Ready for a follow-up.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(5), last_engagement_at: h(5),
    step_count: 1, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(1), updated_at: h(5),
    contact_name: 'Kofi Mensah', contact_email: null, contact_phone: '+233244001234', deal_title: null,
  },
  {
    id: 'a10', workspace_id: 'ws1', contact_id: 'c10', deal_id: 'd6',
    source_type: 'email', source_ref_id: null,
    goal: 'qualification', primary_channel: 'email', fallback_channel: null,
    status: 'escalated', stage: 'handoff_ready',
    priority: 'high', momentum: 'increasing',
    next_action_type: 'handoff', next_action_at: null,
    current_summary: 'Forwarded our email to their VP of Sales with a positive note. Warm intro in progress — needs human follow-up.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(1), last_engagement_at: h(1),
    step_count: 4, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(7), updated_at: h(1),
    contact_name: 'Isabelle Moreau', contact_email: 'isabelle@lumiereco.fr', contact_phone: null, deal_title: 'Lumière Co — Growth',
  },
  {
    id: 'a11', workspace_id: 'ws1', contact_id: 'c31', deal_id: null,
    source_type: 'prospect', source_ref_id: null,
    goal: 'warm_introduction', primary_channel: 'email', fallback_channel: 'sms',
    status: 'engaged', stage: 'engagement_detected',
    priority: 'high', momentum: 'increasing',
    next_action_type: 'send_email', next_action_at: fh(1),
    current_summary: 'Replied with questions about API limits and security compliance. Needs a technical follow-up.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(2), last_engagement_at: h(2),
    step_count: 2, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(3), updated_at: h(2),
    contact_name: 'Aleksei Petrov', contact_email: 'aleksei@datavault.ru', contact_phone: null, deal_title: null,
  },
  {
    id: 'a12', workspace_id: 'ws1', contact_id: 'c32', deal_id: 'd15',
    source_type: 'form', source_ref_id: null,
    goal: 'qualification', primary_channel: 'email', fallback_channel: null,
    status: 'escalated', stage: 'handoff_ready',
    priority: 'high', momentum: 'increasing',
    next_action_type: 'handoff', next_action_at: null,
    current_summary: 'Filled out full qualification survey with budget $50k+. Immediate handoff to account exec.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(0), last_engagement_at: h(0),
    step_count: 3, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(2), updated_at: h(0),
    contact_name: 'Amelia Brooks', contact_email: 'amelia@fincore.co.uk', contact_phone: null, deal_title: 'Fincore — Enterprise',
  },
  {
    id: 'a13', workspace_id: 'ws1', contact_id: 'c33', deal_id: null,
    source_type: 'email', source_ref_id: null,
    goal: 'meeting_conversion', primary_channel: 'email', fallback_channel: 'sms',
    status: 'engaged', stage: 'engagement_detected',
    priority: 'medium', momentum: 'increasing',
    next_action_type: 'send_email', next_action_at: fh(4),
    current_summary: 'Asked to reschedule the demo for next week. Calendar invite sent. High intent confirmed.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(5), last_engagement_at: h(5),
    step_count: 4, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(6), updated_at: h(5),
    contact_name: 'Hassan Al-Farsi', contact_email: 'hassan@gulfdigital.ae', contact_phone: null, deal_title: null,
  },
  {
    id: 'a14', workspace_id: 'ws1', contact_id: 'c34', deal_id: 'd16',
    source_type: 'bot', source_ref_id: null,
    goal: 'warm_introduction', primary_channel: 'sms', fallback_channel: 'email',
    status: 'escalated', stage: 'handoff_ready',
    priority: 'high', momentum: 'increasing',
    next_action_type: 'handoff', next_action_at: null,
    current_summary: 'Responded to SMS within minutes. Requesting a call today. Very high urgency — human needed.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(1), last_engagement_at: h(1),
    step_count: 2, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(1), updated_at: h(1),
    contact_name: 'Brianna Walsh', contact_email: 'brianna@pulsehealth.ie', contact_phone: '+35387654321', deal_title: 'Pulse Health — Team',
  },
  {
    id: 'a15', workspace_id: 'ws1', contact_id: 'c35', deal_id: null,
    source_type: 'prospect', source_ref_id: null,
    goal: 'reengagement', primary_channel: 'email', fallback_channel: null,
    status: 'engaged', stage: 'engagement_detected',
    priority: 'medium', momentum: 'increasing',
    next_action_type: 'send_email', next_action_at: fh(6),
    current_summary: 'Re-opened after 45 days of silence. Clicked the product update link. Re-engagement working.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(8), last_engagement_at: h(8),
    step_count: 5, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(50), updated_at: h(8),
    contact_name: 'Jae-won Oh', contact_email: 'jaewon@seoulsoft.kr', contact_phone: null, deal_title: null,
  },
  {
    id: 'a16', workspace_id: 'ws1', contact_id: 'c36', deal_id: 'd17',
    source_type: 'email', source_ref_id: null,
    goal: 'qualification', primary_channel: 'email', fallback_channel: 'sms',
    status: 'engaged', stage: 'engagement_detected',
    priority: 'high', momentum: 'increasing',
    next_action_type: 'send_email', next_action_at: fh(2),
    current_summary: 'Replied confirming team size is 80 people. Matches ICP exactly. Strong signal for upsell.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(3), last_engagement_at: h(3),
    step_count: 3, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(5), updated_at: h(3),
    contact_name: 'Valeria Cruz', contact_email: 'valeria@latamgrowth.mx', contact_phone: null, deal_title: 'LATAM Growth — Pro',
  },
  {
    id: 'a17', workspace_id: 'ws1', contact_id: 'c37', deal_id: null,
    source_type: 'form', source_ref_id: null,
    goal: 'meeting_conversion', primary_channel: 'email', fallback_channel: 'sms',
    status: 'escalated', stage: 'handoff_ready',
    priority: 'high', momentum: 'increasing',
    next_action_type: 'handoff', next_action_at: null,
    current_summary: 'Booked demo slot directly after first email. Confirmed attendees include their VP of Product.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(2), last_engagement_at: h(2),
    step_count: 1, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(1), updated_at: h(2),
    contact_name: 'Samuel Adeyemi', contact_email: 'samuel@lagosbuild.ng', contact_phone: null, deal_title: null,
  },
  {
    id: 'a18', workspace_id: 'ws1', contact_id: 'c38', deal_id: 'd18',
    source_type: 'prospect', source_ref_id: null,
    goal: 'warm_introduction', primary_channel: 'email', fallback_channel: null,
    status: 'engaged', stage: 'engagement_detected',
    priority: 'medium', momentum: 'flat',
    next_action_type: 'send_email', next_action_at: fd(1),
    current_summary: 'Opened the email 5 times but no reply. Likely evaluating internally. Soft follow-up queued.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(14), last_engagement_at: h(14),
    step_count: 2, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(4), updated_at: h(14),
    contact_name: 'Ingrid Lindström', contact_email: 'ingrid@nordwise.se', contact_phone: null, deal_title: 'Nordwise — Growth',
  },
  {
    id: 'a19', workspace_id: 'ws1', contact_id: 'c39', deal_id: null,
    source_type: 'bot', source_ref_id: null,
    goal: 'qualification', primary_channel: 'sms', fallback_channel: 'email',
    status: 'engaged', stage: 'engagement_detected',
    priority: 'medium', momentum: 'increasing',
    next_action_type: 'send_sms', next_action_at: fh(3),
    current_summary: 'Replied "interested, tell me more" to cold SMS. Moving to qualification stage.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(6), last_engagement_at: h(6),
    step_count: 1, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(1), updated_at: h(6),
    contact_name: 'Mehmet Yılmaz', contact_email: null, contact_phone: '+905321234567', deal_title: null,
  },
  {
    id: 'a20', workspace_id: 'ws1', contact_id: 'c40', deal_id: 'd19',
    source_type: 'email', source_ref_id: null,
    goal: 'meeting_conversion', primary_channel: 'email', fallback_channel: 'sms',
    status: 'escalated', stage: 'handoff_ready',
    priority: 'high', momentum: 'increasing',
    next_action_type: 'handoff', next_action_at: null,
    current_summary: 'Second reply mentioned their board approved budget last week. Urgency is real — escalate now.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(0), last_engagement_at: h(0),
    step_count: 4, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(7), updated_at: h(0),
    contact_name: 'Nadia Osei', contact_email: 'nadia@accraventures.gh', contact_phone: null, deal_title: 'Accra Ventures — Enterprise',
  },

  // ── Active (running / waiting) — 10 leads ────────────────────────────────
  {
    id: 'b1', workspace_id: 'ws1', contact_id: 'c11', deal_id: null,
    source_type: 'prospect', source_ref_id: null,
    goal: 'qualification', primary_channel: 'email', fallback_channel: null,
    status: 'running', stage: 'follow_up',
    priority: 'medium', momentum: 'flat',
    next_action_type: 'send_email', next_action_at: fd(1),
    current_summary: 'Sent intro email 3 days ago. No reply yet. Follow-up scheduled for tomorrow.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(3), last_engagement_at: null,
    step_count: 1, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(5), updated_at: d(3),
    contact_name: 'James Okafor', contact_email: 'james@brightpath.io', contact_phone: null, deal_title: 'Brightpath — Growth Plan',
  },
  {
    id: 'b2', workspace_id: 'ws1', contact_id: 'c12', deal_id: null,
    source_type: 'prospect', source_ref_id: null,
    goal: 'reengagement', primary_channel: 'sms', fallback_channel: null,
    status: 'waiting', stage: 'nurture',
    priority: 'low', momentum: 'declining',
    next_action_type: 'wait', next_action_at: fd(5),
    current_summary: 'Went cold after initial contact 3 weeks ago. Re-engagement sequence started via SMS.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(7), last_engagement_at: null,
    step_count: 3, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(21), updated_at: d(7),
    contact_name: 'Priya Nair', contact_email: 'priya@novatech.in', contact_phone: '+447700900123', deal_title: null,
  },
  {
    id: 'b3', workspace_id: 'ws1', contact_id: 'c13', deal_id: 'd7',
    source_type: 'email', source_ref_id: null,
    goal: 'warm_introduction', primary_channel: 'email', fallback_channel: 'sms',
    status: 'running', stage: 'initial_outreach',
    priority: 'medium', momentum: 'flat',
    next_action_type: 'send_email', next_action_at: fd(2),
    current_summary: 'First outreach email delivered. Waiting for engagement window to pass before follow-up.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(1), last_engagement_at: null,
    step_count: 1, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(1), updated_at: d(1),
    contact_name: 'Daniel Weiss', contact_email: 'daniel@vertexai.io', contact_phone: null, deal_title: 'Vertex AI — Pilot',
  },
  {
    id: 'b4', workspace_id: 'ws1', contact_id: 'c14', deal_id: null,
    source_type: 'bot', source_ref_id: null,
    goal: 'qualification', primary_channel: 'sms', fallback_channel: 'email',
    status: 'running', stage: 'follow_up',
    priority: 'medium', momentum: 'flat',
    next_action_type: 'send_sms', next_action_at: fh(8),
    current_summary: 'Second touchpoint sent. Opened but no response. Nudge scheduled via SMS.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(2), last_engagement_at: null,
    step_count: 2, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(4), updated_at: d(2),
    contact_name: 'Amara Diallo', contact_email: 'amara@kintech.sn', contact_phone: '+221776543210', deal_title: null,
  },
  {
    id: 'b5', workspace_id: 'ws1', contact_id: 'c15', deal_id: 'd8',
    source_type: 'form', source_ref_id: null,
    goal: 'meeting_conversion', primary_channel: 'email', fallback_channel: null,
    status: 'waiting', stage: 'nurture',
    priority: 'low', momentum: 'flat',
    next_action_type: 'wait', next_action_at: fd(3),
    current_summary: 'Booked a slot but cancelled last minute. Waiting 3 days before sending reschedule email.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(2), last_engagement_at: d(2),
    step_count: 3, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(8), updated_at: d(2),
    contact_name: 'Ravi Shankar', contact_email: 'ravi@stackops.in', contact_phone: null, deal_title: 'StackOps — Enterprise',
  },
  {
    id: 'b6', workspace_id: 'ws1', contact_id: 'c16', deal_id: null,
    source_type: 'prospect', source_ref_id: null,
    goal: 'warm_introduction', primary_channel: 'email', fallback_channel: null,
    status: 'running', stage: 'initial_outreach',
    priority: 'medium', momentum: 'flat',
    next_action_type: 'send_email', next_action_at: fd(1),
    current_summary: 'Cold lead from enrichment. Intro email queued for tomorrow morning based on timezone.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(0), last_engagement_at: null,
    step_count: 0, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(0), updated_at: d(0),
    contact_name: 'Sofia Andersson', contact_email: 'sofia@northloop.se', contact_phone: null, deal_title: null,
  },
  {
    id: 'b7', workspace_id: 'ws1', contact_id: 'c17', deal_id: null,
    source_type: 'email', source_ref_id: null,
    goal: 'reengagement', primary_channel: 'email', fallback_channel: 'sms',
    status: 'running', stage: 'nurture',
    priority: 'low', momentum: 'declining',
    next_action_type: 'send_email', next_action_at: fd(4),
    current_summary: 'Last contacted 2 months ago. Re-engagement campaign at step 2. Low engagement so far.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(5), last_engagement_at: null,
    step_count: 2, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(60), updated_at: d(5),
    contact_name: 'Tariq Al-Hassan', contact_email: 'tariq@menaventures.com', contact_phone: null, deal_title: null,
  },
  {
    id: 'b8', workspace_id: 'ws1', contact_id: 'c18', deal_id: 'd9',
    source_type: 'bot', source_ref_id: null,
    goal: 'qualification', primary_channel: 'sms', fallback_channel: null,
    status: 'waiting', stage: 'qualification',
    priority: 'medium', momentum: 'flat',
    next_action_type: 'wait', next_action_at: fd(2),
    current_summary: 'Gathering qualification data via SMS. Waiting for reply to company-size question.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(18), last_engagement_at: null,
    step_count: 2, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(3), updated_at: h(18),
    contact_name: 'Chloe Dupont', contact_email: 'chloe@agencepulse.fr', contact_phone: '+33612345678', deal_title: 'Agence Pulse — Growth',
  },
  {
    id: 'b9', workspace_id: 'ws1', contact_id: 'c19', deal_id: null,
    source_type: 'prospect', source_ref_id: null,
    goal: 'warm_introduction', primary_channel: 'email', fallback_channel: 'sms',
    status: 'running', stage: 'follow_up',
    priority: 'medium', momentum: 'flat',
    next_action_type: 'send_email', next_action_at: fd(1),
    current_summary: 'Third follow-up email in sequence. Opened 2 of 3 emails. No reply yet.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(4), last_engagement_at: null,
    step_count: 3, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(10), updated_at: d(4),
    contact_name: 'Emeka Nwosu', contact_email: 'emeka@tradehub.ng', contact_phone: null, deal_title: null,
  },
  {
    id: 'b10', workspace_id: 'ws1', contact_id: 'c20', deal_id: 'd10',
    source_type: 'form', source_ref_id: null,
    goal: 'meeting_conversion', primary_channel: 'email', fallback_channel: 'sms',
    status: 'running', stage: 'follow_up',
    priority: 'high', momentum: 'flat',
    next_action_type: 'send_email', next_action_at: fh(6),
    current_summary: 'Demo request submitted via web form. Confirmation email sent. Reminder queued 6 hours before slot.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(2), last_engagement_at: h(2),
    step_count: 2, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(1), updated_at: h(2),
    contact_name: 'Zara Khan', contact_email: 'zara@techbridge.pk', contact_phone: null, deal_title: 'TechBridge — Starter',
  },
  {
    id: 'b11', workspace_id: 'ws1', contact_id: 'c41', deal_id: null,
    source_type: 'prospect', source_ref_id: null,
    goal: 'warm_introduction', primary_channel: 'email', fallback_channel: null,
    status: 'running', stage: 'initial_outreach',
    priority: 'medium', momentum: 'flat',
    next_action_type: 'send_email', next_action_at: fd(2),
    current_summary: 'New enriched lead. First touch email scheduled. No engagement yet.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(0), last_engagement_at: null,
    step_count: 0, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(0), updated_at: d(0),
    contact_name: 'Lucas Fontaine', contact_email: 'lucas@alpinedigital.ch', contact_phone: null, deal_title: null,
  },
  {
    id: 'b12', workspace_id: 'ws1', contact_id: 'c42', deal_id: 'd20',
    source_type: 'form', source_ref_id: null,
    goal: 'qualification', primary_channel: 'email', fallback_channel: 'sms',
    status: 'waiting', stage: 'qualification',
    priority: 'medium', momentum: 'flat',
    next_action_type: 'wait', next_action_at: fd(4),
    current_summary: 'Qualification email delivered. No reply in 2 days. Waiting before SMS nudge.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(2), last_engagement_at: null,
    step_count: 1, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(3), updated_at: d(2),
    contact_name: 'Thabo Nkosi', contact_email: 'thabo@cape-ventures.za', contact_phone: null, deal_title: 'Cape Ventures — Growth',
  },
  {
    id: 'b13', workspace_id: 'ws1', contact_id: 'c43', deal_id: null,
    source_type: 'bot', source_ref_id: null,
    goal: 'reengagement', primary_channel: 'sms', fallback_channel: 'email',
    status: 'running', stage: 'nurture',
    priority: 'low', momentum: 'declining',
    next_action_type: 'send_sms', next_action_at: fd(3),
    current_summary: 'Dormant for 6 weeks. Re-engagement SMS sequence at step 2. Monitoring for signal.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(9), last_engagement_at: null,
    step_count: 2, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(45), updated_at: d(9),
    contact_name: 'Linh Nguyen', contact_email: 'linh@hanoitech.vn', contact_phone: '+84912345678', deal_title: null,
  },
  {
    id: 'b14', workspace_id: 'ws1', contact_id: 'c44', deal_id: 'd21',
    source_type: 'email', source_ref_id: null,
    goal: 'meeting_conversion', primary_channel: 'email', fallback_channel: null,
    status: 'running', stage: 'follow_up',
    priority: 'high', momentum: 'flat',
    next_action_type: 'send_email', next_action_at: fh(10),
    current_summary: 'Demo request from inbound email. Confirmation sent. Pre-demo check-in scheduled.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(4), last_engagement_at: h(4),
    step_count: 2, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(2), updated_at: h(4),
    contact_name: 'Olumide Adewale', contact_email: 'olumide@techprime.ng', contact_phone: null, deal_title: 'TechPrime — Business',
  },
  {
    id: 'b15', workspace_id: 'ws1', contact_id: 'c45', deal_id: null,
    source_type: 'prospect', source_ref_id: null,
    goal: 'warm_introduction', primary_channel: 'email', fallback_channel: 'sms',
    status: 'waiting', stage: 'follow_up',
    priority: 'medium', momentum: 'flat',
    next_action_type: 'wait', next_action_at: fd(2),
    current_summary: 'Follow-up 2 sent yesterday. Waiting for 48h engagement window before next step.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(1), last_engagement_at: null,
    step_count: 2, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(5), updated_at: d(1),
    contact_name: 'Anastasia Popova', contact_email: 'anastasia@sibtech.ru', contact_phone: null, deal_title: null,
  },
  {
    id: 'b16', workspace_id: 'ws1', contact_id: 'c46', deal_id: null,
    source_type: 'bot', source_ref_id: null,
    goal: 'qualification', primary_channel: 'sms', fallback_channel: null,
    status: 'running', stage: 'qualification',
    priority: 'low', momentum: 'flat',
    next_action_type: 'send_sms', next_action_at: fd(1),
    current_summary: 'Qualification bot conversation at step 3. Asking about tech stack.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(2), last_engagement_at: null,
    step_count: 3, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(4), updated_at: d(2),
    contact_name: 'Kwabena Asante', contact_email: 'kwabena@goldcoastops.gh', contact_phone: '+233244556677', deal_title: null,
  },
  {
    id: 'b17', workspace_id: 'ws1', contact_id: 'c47', deal_id: 'd22',
    source_type: 'form', source_ref_id: null,
    goal: 'meeting_conversion', primary_channel: 'email', fallback_channel: 'sms',
    status: 'running', stage: 'nurture',
    priority: 'medium', momentum: 'flat',
    next_action_type: 'send_email', next_action_at: fd(3),
    current_summary: 'Attended webinar last week. Nurture sequence triggered. Step 1 sent.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(3), last_engagement_at: d(7),
    step_count: 1, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(8), updated_at: d(3),
    contact_name: 'Petra Horáková', contact_email: 'petra@praguetech.cz', contact_phone: null, deal_title: 'Prague Tech — Starter',
  },
  {
    id: 'b18', workspace_id: 'ws1', contact_id: 'c48', deal_id: null,
    source_type: 'prospect', source_ref_id: null,
    goal: 'reengagement', primary_channel: 'email', fallback_channel: null,
    status: 'waiting', stage: 'nurture',
    priority: 'low', momentum: 'declining',
    next_action_type: 'wait', next_action_at: fd(6),
    current_summary: 'Contact on summer break until next week. Sequence paused for 7 days, then resumes.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(3), last_engagement_at: null,
    step_count: 1, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(10), updated_at: d(3),
    contact_name: 'Enzo Ricci', contact_email: 'enzo@milanomade.it', contact_phone: null, deal_title: null,
  },
  {
    id: 'b19', workspace_id: 'ws1', contact_id: 'c49', deal_id: 'd23',
    source_type: 'email', source_ref_id: null,
    goal: 'warm_introduction', primary_channel: 'email', fallback_channel: 'sms',
    status: 'running', stage: 'initial_outreach',
    priority: 'medium', momentum: 'flat',
    next_action_type: 'send_email', next_action_at: fd(2),
    current_summary: 'Warm intro sequence started based on recent LinkedIn activity. Step 1 sent.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(1), last_engagement_at: null,
    step_count: 1, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(2), updated_at: d(1),
    contact_name: 'Chiara Ferrara', contact_email: 'chiara@romadigital.it', contact_phone: null, deal_title: 'Roma Digital — Pro',
  },
  {
    id: 'b20', workspace_id: 'ws1', contact_id: 'c50', deal_id: null,
    source_type: 'bot', source_ref_id: null,
    goal: 'qualification', primary_channel: 'sms', fallback_channel: 'email',
    status: 'running', stage: 'follow_up',
    priority: 'medium', momentum: 'flat',
    next_action_type: 'send_sms', next_action_at: fh(12),
    current_summary: 'SMS delivered. Read receipt confirmed. No reply. Evening nudge queued.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: h(6), last_engagement_at: null,
    step_count: 2, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(2), updated_at: h(6),
    contact_name: 'Ibrahim Traoré', contact_email: null, contact_phone: '+22676543210', deal_title: null,
  },

  // ── Stopped / Cancelled (paused / stopped / completed) — 10 leads ─────────
  {
    id: 'c1', workspace_id: 'ws1', contact_id: 'c21', deal_id: null,
    source_type: 'bot', source_ref_id: null,
    goal: 'qualification', primary_channel: 'sms', fallback_channel: null,
    status: 'paused', stage: 'follow_up',
    priority: 'medium', momentum: 'flat',
    next_action_type: null, next_action_at: null,
    current_summary: 'Paused after SMS opt-out keyword detected. Awaiting manual review.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(2), last_engagement_at: null,
    step_count: 1, paused_at: d(2), paused_reason: 'SMS opt-out detected',
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(4), updated_at: d(2),
    contact_name: 'Aisha Kamara', contact_email: null, contact_phone: '+12125559876', deal_title: null,
  },
  {
    id: 'c2', workspace_id: 'ws1', contact_id: 'c22', deal_id: null,
    source_type: 'prospect', source_ref_id: null,
    goal: 'warm_introduction', primary_channel: 'email', fallback_channel: null,
    status: 'stopped', stage: 'initial_outreach',
    priority: 'low', momentum: 'declining',
    next_action_type: null, next_action_at: null,
    current_summary: 'Stopped after 5 attempts with no engagement. Marked as unresponsive.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(14), last_engagement_at: null,
    step_count: 5, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: d(7), stopped_reason: 'No engagement after 5 attempts',
    created_at: d(30), updated_at: d(7),
    contact_name: 'Haruto Yamamoto', contact_email: 'haruto@tekken.jp', contact_phone: null, deal_title: null,
  },
  {
    id: 'c3', workspace_id: 'ws1', contact_id: 'c23', deal_id: 'd11',
    source_type: 'email', source_ref_id: null,
    goal: 'meeting_conversion', primary_channel: 'email', fallback_channel: null,
    status: 'completed', stage: 'closed',
    priority: 'medium', momentum: 'flat',
    next_action_type: null, next_action_at: null,
    current_summary: 'Successfully booked a discovery call. Automation completed and handed off to sales.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(3), last_engagement_at: d(3),
    step_count: 6, paused_at: null, paused_reason: null,
    completed_at: d(3), stopped_at: null, stopped_reason: null,
    created_at: d(18), updated_at: d(3),
    contact_name: 'Olga Kravets', contact_email: 'olga@igniteco.ua', contact_phone: null, deal_title: 'Ignite Co — Pro',
  },
  {
    id: 'c4', workspace_id: 'ws1', contact_id: 'c24', deal_id: null,
    source_type: 'bot', source_ref_id: null,
    goal: 'reengagement', primary_channel: 'sms', fallback_channel: 'email',
    status: 'paused', stage: 'nurture',
    priority: 'low', momentum: 'declining',
    next_action_type: null, next_action_at: null,
    current_summary: 'Paused manually. Contact requested to be contacted only after their fiscal year ends.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(10), last_engagement_at: null,
    step_count: 2, paused_at: d(10), paused_reason: 'Contact requested pause until Q1',
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(25), updated_at: d(10),
    contact_name: 'Bart van der Berg', contact_email: 'bart@benelux-ops.nl', contact_phone: null, deal_title: null,
  },
  {
    id: 'c5', workspace_id: 'ws1', contact_id: 'c25', deal_id: 'd12',
    source_type: 'form', source_ref_id: null,
    goal: 'qualification', primary_channel: 'email', fallback_channel: null,
    status: 'completed', stage: 'closed',
    priority: 'high', momentum: 'flat',
    next_action_type: null, next_action_at: null,
    current_summary: 'Fully qualified. Deal created and passed to account executive. Automation closed.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(5), last_engagement_at: d(5),
    step_count: 7, paused_at: null, paused_reason: null,
    completed_at: d(5), stopped_at: null, stopped_reason: null,
    created_at: d(20), updated_at: d(5),
    contact_name: 'Maria Santos', contact_email: 'maria@iberiasolutions.es', contact_phone: null, deal_title: 'Iberia Solutions — Team',
  },
  {
    id: 'c6', workspace_id: 'ws1', contact_id: 'c26', deal_id: null,
    source_type: 'prospect', source_ref_id: null,
    goal: 'warm_introduction', primary_channel: 'email', fallback_channel: 'sms',
    status: 'stopped', stage: 'initial_outreach',
    priority: 'low', momentum: 'declining',
    next_action_type: null, next_action_at: null,
    current_summary: 'Stopped — contact unsubscribed from email.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(8), last_engagement_at: null,
    step_count: 2, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: d(8), stopped_reason: 'Contact unsubscribed',
    created_at: d(15), updated_at: d(8),
    contact_name: 'Nguyen Phuong', contact_email: 'phuong@saigontech.vn', contact_phone: null, deal_title: null,
  },
  {
    id: 'c7', workspace_id: 'ws1', contact_id: 'c27', deal_id: null,
    source_type: 'email', source_ref_id: null,
    goal: 'reengagement', primary_channel: 'email', fallback_channel: null,
    status: 'paused', stage: 'nurture',
    priority: 'medium', momentum: 'flat',
    next_action_type: null, next_action_at: null,
    current_summary: 'Email bounced — deliverability issue. Paused pending contact info update.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(6), last_engagement_at: null,
    step_count: 1, paused_at: d(6), paused_reason: 'Email bounced',
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(9), updated_at: d(6),
    contact_name: 'Elena Volkov', contact_email: 'elena@digitalstep.ru', contact_phone: null, deal_title: null,
  },
  {
    id: 'c8', workspace_id: 'ws1', contact_id: 'c28', deal_id: 'd13',
    source_type: 'bot', source_ref_id: null,
    goal: 'meeting_conversion', primary_channel: 'sms', fallback_channel: 'email',
    status: 'completed', stage: 'closed',
    priority: 'medium', momentum: 'flat',
    next_action_type: null, next_action_at: null,
    current_summary: 'Demo booked and attended. Proposal sent by sales. Automation marked complete.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(7), last_engagement_at: d(7),
    step_count: 5, paused_at: null, paused_reason: null,
    completed_at: d(7), stopped_at: null, stopped_reason: null,
    created_at: d(22), updated_at: d(7),
    contact_name: 'Kwame Boateng', contact_email: 'kwame@accratech.gh', contact_phone: '+233302123456', deal_title: 'AccraTech — Business',
  },
  {
    id: 'c9', workspace_id: 'ws1', contact_id: 'c29', deal_id: null,
    source_type: 'prospect', source_ref_id: null,
    goal: 'qualification', primary_channel: 'email', fallback_channel: null,
    status: 'stopped', stage: 'follow_up',
    priority: 'low', momentum: 'declining',
    next_action_type: null, next_action_at: null,
    current_summary: 'Stopped — duplicate contact merged. Automation replaced by a fresh sequence.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(12), last_engagement_at: null,
    step_count: 3, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: d(12), stopped_reason: 'Duplicate — merged',
    created_at: d(20), updated_at: d(12),
    contact_name: 'Silvia Greco', contact_email: 'silvia@neovision.it', contact_phone: null, deal_title: null,
  },
  {
    id: 'c10', workspace_id: 'ws1', contact_id: 'c30', deal_id: 'd14',
    source_type: 'form', source_ref_id: null,
    goal: 'warm_introduction', primary_channel: 'email', fallback_channel: 'sms',
    status: 'completed', stage: 'closed',
    priority: 'high', momentum: 'flat',
    next_action_type: null, next_action_at: null,
    current_summary: 'Lead converted to customer. Signed a 12-month contract. Automation closed successfully.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(4), last_engagement_at: d(4),
    step_count: 8, paused_at: null, paused_reason: null,
    completed_at: d(4), stopped_at: null, stopped_reason: null,
    created_at: d(30), updated_at: d(4),
    contact_name: 'Carlos Rivera', contact_email: 'carlos@solargroup.mx', contact_phone: null, deal_title: 'Solar Group — Annual',
  },
  {
    id: 'c11', workspace_id: 'ws1', contact_id: 'c51', deal_id: null,
    source_type: 'prospect', source_ref_id: null,
    goal: 'warm_introduction', primary_channel: 'email', fallback_channel: null,
    status: 'stopped', stage: 'initial_outreach',
    priority: 'low', momentum: 'declining',
    next_action_type: null, next_action_at: null,
    current_summary: 'Stopped — contact email hard-bounced on all 3 attempts.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(10), last_engagement_at: null,
    step_count: 3, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: d(10), stopped_reason: 'Hard bounce',
    created_at: d(20), updated_at: d(10),
    contact_name: 'Dmitri Volkov', contact_email: 'dmitri@old-domain.ru', contact_phone: null, deal_title: null,
  },
  {
    id: 'c12', workspace_id: 'ws1', contact_id: 'c52', deal_id: 'd24',
    source_type: 'email', source_ref_id: null,
    goal: 'qualification', primary_channel: 'email', fallback_channel: null,
    status: 'completed', stage: 'closed',
    priority: 'high', momentum: 'flat',
    next_action_type: null, next_action_at: null,
    current_summary: 'Qualified and passed to sales. Closed-won deal at $18k ARR.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(2), last_engagement_at: d(2),
    step_count: 5, paused_at: null, paused_reason: null,
    completed_at: d(2), stopped_at: null, stopped_reason: null,
    created_at: d(14), updated_at: d(2),
    contact_name: 'Maya Goldstein', contact_email: 'maya@tlvtech.il', contact_phone: null, deal_title: 'TLV Tech — Annual Pro',
  },
  {
    id: 'c13', workspace_id: 'ws1', contact_id: 'c53', deal_id: null,
    source_type: 'bot', source_ref_id: null,
    goal: 'reengagement', primary_channel: 'sms', fallback_channel: null,
    status: 'paused', stage: 'nurture',
    priority: 'medium', momentum: 'flat',
    next_action_type: null, next_action_at: null,
    current_summary: 'Paused — contact filed a dispute. Awaiting legal team clearance.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(5), last_engagement_at: null,
    step_count: 1, paused_at: d(5), paused_reason: 'Legal hold',
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(8), updated_at: d(5),
    contact_name: 'Antoine Lemaire', contact_email: 'antoine@lyongroup.fr', contact_phone: null, deal_title: null,
  },
  {
    id: 'c14', workspace_id: 'ws1', contact_id: 'c54', deal_id: 'd25',
    source_type: 'form', source_ref_id: null,
    goal: 'meeting_conversion', primary_channel: 'email', fallback_channel: 'sms',
    status: 'completed', stage: 'closed',
    priority: 'medium', momentum: 'flat',
    next_action_type: null, next_action_at: null,
    current_summary: 'Demo attended. Trial started. Automation closed, CRM deal in negotiation stage.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(6), last_engagement_at: d(6),
    step_count: 4, paused_at: null, paused_reason: null,
    completed_at: d(6), stopped_at: null, stopped_reason: null,
    created_at: d(15), updated_at: d(6),
    contact_name: 'Florencia Méndez', contact_email: 'florencia@buenosairesai.ar', contact_phone: null, deal_title: 'BsAs AI — Growth',
  },
  {
    id: 'c15', workspace_id: 'ws1', contact_id: 'c55', deal_id: null,
    source_type: 'prospect', source_ref_id: null,
    goal: 'warm_introduction', primary_channel: 'email', fallback_channel: 'sms',
    status: 'stopped', stage: 'follow_up',
    priority: 'low', momentum: 'declining',
    next_action_type: null, next_action_at: null,
    current_summary: 'Stopped — 6 attempts, 0 opens. Domain possibly blocking our emails.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(18), last_engagement_at: null,
    step_count: 6, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: d(18), stopped_reason: 'Zero opens — possible spam block',
    created_at: d(40), updated_at: d(18),
    contact_name: 'Piotr Kowalski', contact_email: 'piotr@warsaw-ops.pl', contact_phone: null, deal_title: null,
  },
  {
    id: 'c16', workspace_id: 'ws1', contact_id: 'c56', deal_id: 'd26',
    source_type: 'email', source_ref_id: null,
    goal: 'qualification', primary_channel: 'email', fallback_channel: null,
    status: 'completed', stage: 'closed',
    priority: 'high', momentum: 'flat',
    next_action_type: null, next_action_at: null,
    current_summary: 'Lead qualified, deal created, intro call completed. Marked as converted.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(3), last_engagement_at: d(3),
    step_count: 6, paused_at: null, paused_reason: null,
    completed_at: d(3), stopped_at: null, stopped_reason: null,
    created_at: d(16), updated_at: d(3),
    contact_name: 'Sun Li', contact_email: 'sunli@shanghaigrowth.cn', contact_phone: null, deal_title: 'Shanghai Growth — Enterprise',
  },
  {
    id: 'c17', workspace_id: 'ws1', contact_id: 'c57', deal_id: null,
    source_type: 'bot', source_ref_id: null,
    goal: 'reengagement', primary_channel: 'sms', fallback_channel: 'email',
    status: 'paused', stage: 'nurture',
    priority: 'low', momentum: 'declining',
    next_action_type: null, next_action_at: null,
    current_summary: 'Paused — contact replied "not now" to re-engagement SMS. Respecting the signal.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(9), last_engagement_at: d(9),
    step_count: 2, paused_at: d(9), paused_reason: 'Contact said not now',
    completed_at: null, stopped_at: null, stopped_reason: null,
    created_at: d(30), updated_at: d(9),
    contact_name: 'Omar Benali', contact_email: 'omar@algiersinnovate.dz', contact_phone: '+213661234567', deal_title: null,
  },
  {
    id: 'c18', workspace_id: 'ws1', contact_id: 'c58', deal_id: 'd27',
    source_type: 'prospect', source_ref_id: null,
    goal: 'meeting_conversion', primary_channel: 'email', fallback_channel: null,
    status: 'completed', stage: 'closed',
    priority: 'medium', momentum: 'flat',
    next_action_type: null, next_action_at: null,
    current_summary: 'Meeting held, proposal accepted. Automation closed after successful conversion.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(8), last_engagement_at: d(8),
    step_count: 7, paused_at: null, paused_reason: null,
    completed_at: d(8), stopped_at: null, stopped_reason: null,
    created_at: d(25), updated_at: d(8),
    contact_name: 'Yewande Adebayo', contact_email: 'yewande@lagossaas.ng', contact_phone: null, deal_title: 'Lagos SaaS — Team',
  },
  {
    id: 'c19', workspace_id: 'ws1', contact_id: 'c59', deal_id: null,
    source_type: 'form', source_ref_id: null,
    goal: 'warm_introduction', primary_channel: 'email', fallback_channel: 'sms',
    status: 'stopped', stage: 'initial_outreach',
    priority: 'low', momentum: 'declining',
    next_action_type: null, next_action_at: null,
    current_summary: 'Stopped — contact registered with a competitor. Removed from active pipeline.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(11), last_engagement_at: null,
    step_count: 2, paused_at: null, paused_reason: null,
    completed_at: null, stopped_at: d(11), stopped_reason: 'Went with competitor',
    created_at: d(18), updated_at: d(11),
    contact_name: 'Rafael Montoya', contact_email: 'rafael@bogotaops.co', contact_phone: null, deal_title: null,
  },
  {
    id: 'c20', workspace_id: 'ws1', contact_id: 'c60', deal_id: 'd28',
    source_type: 'email', source_ref_id: null,
    goal: 'qualification', primary_channel: 'email', fallback_channel: 'sms',
    status: 'completed', stage: 'closed',
    priority: 'high', momentum: 'flat',
    next_action_type: null, next_action_at: null,
    current_summary: 'Full qualification done. 3-seat deal signed. Automation completed and archived.',
    current_reasoning: null, ai_strategy: {}, qualification: {},
    last_activity_at: d(1), last_engagement_at: d(1),
    step_count: 5, paused_at: null, paused_reason: null,
    completed_at: d(1), stopped_at: null, stopped_reason: null,
    created_at: d(12), updated_at: d(1),
    contact_name: 'Hana Novák', contact_email: 'hana@bratislavatech.sk', contact_phone: null, deal_title: 'Bratislava Tech — Pro',
  },
]

const MOCK_INSIGHTS = { active: 20, engaged: 8, escalated: 6, completed: 6 }

export default async function AutomationsPage() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const { data: membershipRaw } = await supabase
    .from('workspace_members')
    .select('workspace_id')
    .eq('user_id', user.id)
    .order('created_at', { ascending: true })
    .limit(1)
    .single()
  const workspaceId = (membershipRaw as { workspace_id: string } | null)?.workspace_id
  if (!workspaceId) redirect('/login')

  const activityDate = new Date().toISOString().slice(0, 10)
  const [activity, viewingAs] = await Promise.all([
    getActivityFeed(user.id, workspaceId, activityDate),
    resolveViewingAs(undefined, workspaceId),
  ])

  // TODO: replace mock with real data once migration is stable:
  // const [active, insights] = await Promise.all([getActiveAutomations(), getAutomationInsights()])

  return (
    <div className="flex flex-col flex-1 min-h-0 overflow-hidden">
      <SageToolbar pageKey="automations" />
      <div className="flex-1 min-h-0 overflow-hidden">
        <AutomationsClient
          active={MOCK_ACTIVE}
          insights={MOCK_INSIGHTS}
          activity={activity}
          activityDate={activityDate}
          viewingAs={viewingAs}
        />
      </div>
    </div>
  )
}
